### ISSUE TITLE
GoBinEnv GORPIVATE can't effect

### ISSUE THREAD

**Issue by LincolnBruce** [goproxy/goproxy#11]
`package main

import (
	"net/http"
	"os"
	"github.com/goproxy/goproxy"
)

func main(){
	g := goproxy.New()
	g.GoBinEnv = append(
		os.Environ(),
		"GOPROXY=https://goproxy.cn,direct", // 使用 goproxy.cn 作为上游代理
		"GOPRIVATE=gitlab.xx.com",         // 解决私有模块的拉取问题（比如可以配置成公司内部的代码源）
	)
	g.ProxiedSUMDBs = []string{"sum.golang.org https://goproxy.cn/sumdb/sum.golang.org"} // 代理默认的校验和数据库
	http.ListenAndServe("0.0.0.0:80", g)
}
`

**Comment by aofei** [comment]
Please describe your problem in more detail. What do you mean it can't take effect? And, how did you use the service you built with this code?

**Comment by aofei** [comment]
Since you haven't responded in a long time, I'll close this issue. If you have any other questions, please feel free to ask them.
