### ISSUE TITLE
Using cacher.Disk

### ISSUE THREAD

**Issue by ramzis** [goproxy/goproxy#12]
What is the value of Root supposed/is intended to be when creating cacher.Disk? 
It is commented as 'Root is the root of the caches.'

    gp := goproxy.New()
    gp.Cacher = &cacher.Disk{Root: "?"}

**Comment by aofei** [comment]
It's a path of a directory on your disk. Such as: /home/jon/my-goproxy-caches

All caches will be stored in this Root directory.

Sorry for the obscure doc.
