### ISSUE TITLE
MITM

### ISSUE THREAD

**Issue by vbisbest** [goproxy/goproxy#18]
Is it correct that this does not support MITM as the original goproxy does?

**Comment by aofei** [comment]
Since Go has [checksum database](https://golang.org/design/25530-sumdb), there is no way for a Go module proxy to perform MITM attacks.

**Comment by aofei** [comment]
Ah, sorry, I think you found the wrong project, this project is for the Go programming language, not for the traditional system-wide proxying. Closing.
