### ISSUE TITLE
导入出错

### ISSUE THREAD

**Issue by zoulux** [goproxy/goproxy#19]
GOPROXY=http://localhost:8080 go get github.com/siddontang/go-mysql/mysql

---
2021/05/20 17:57:21 github.com@latest: invalid github.com import path "github.com"
2021/05/20 17:57:22 github.com/siddontang@latest: invalid github.com import path "github.com/siddontang"
2021/05/20 18:00:09 github.com/siddontang/go-mysql/mysql@latest: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/jake/go/pkg/mod/cache/vcs/92894505ca13a7c5b28497893ecf5a15e514a6846dce0982e06fd86323d1c118: exit status 128:
        fatal: unable to access 'https://github.com/siddontang/go-mysql/': Failed to connect to github.com port 443: Operation timed out

**Comment by aofei** [comment]
Looks like your local network error. Please check the local network your Goproxy program is running on, or specify an **upstream proxy** for it like [this](https://goproxy.cn/#self-hosted-go-module-proxy).

**Comment by zoulux** [comment]
```go
package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"

	"github.com/goproxy/goproxy"
)

var cacheDir string

func init() {
	flag.StringVar(&cacheDir, "cache", "cache", "缓存路径")
	flag.Parse()
}

func main() {

	err := http.ListenAndServe("localhost:8080", &goproxy.Goproxy{
		GoBinEnv: append(
			os.Environ(),
			"GOPROXY=https://goproxy.cn,direct", // 使用 Goproxy.cn 作为上游代理
			"GOPRIVATE=git.datagrand.com",       // 解决私有模块的拉取问题（比如可以配置成公司内部的代码源）
		),
		ProxiedSUMDBs: []string{
			"sum.golang.org https://goproxy.cn/sumdb/sum.golang.org", // 代理默认的校验和数据库
		},
		Cacher: goproxy.DirCacher("/Users/jake/workspace/goproxy/cache"),
	})

	if err != nil {
		fmt.Println(err.Error())
		return
	}
}

```

**Comment by zoulux** [comment]
这是源码，可以测试一下

**Comment by aofei** [comment]
同样的代码，我这里跑着是不存在任何问题的。

> 2021/05/20 18:00:09 github.com/siddontang/go-mysql/mysql@latest: git fetch -f origin refs/heads/:refs/heads/ refs/tags/:refs/tags/ in ...
> fatal: unable to access 'https://github.com/siddontang/go-mysql/': Failed to connect to github.com port 443: Operation timed out

这个错误指的是你程序所跑在的本地网络存在问题，所跑环境无法访问到 `github.com:443`，和你的代码本身是无关的。

**Comment by aofei** [comment]
鉴于问题已回答，这个 issue 我就先关闭了哈，如果还有其他问题欢迎随时开新 issue 提问～
