### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by gcstang** [goproxy/goproxy#22]
When using this proxy shouldn't any mods that are updated through it be pulled down and cached?

**Comment by aofei** [comment]
They will be cached if you set the [goproxy.Goproxy.Cacher](https://pkg.go.dev/github.com/goproxy/goproxy#Goproxy.Cacher).

**Comment by gcstang** [comment]
I did that but not everything is cached

**Comment by aofei** [comment]
Which ones are not cached? Please provide some cases.

**Comment by aofei** [comment]
It should be noted that if you use an upstream proxy (defaulted to `https://proxy.golang.org`), only the file you requested, (`.info`, `.mod`, or `.zip`) will be cached, not three at a time, because that would be time-consuming (if there is a large `.zip`). And if you want to cache three at a time, then you can explicitly set the `GOPROXY` environment variable via [`goproxy.Goproxy.GoBinEnv`](https://pkg.go.dev/github.com/goproxy/goproxy#Goproxy.GoBinEnv) to `direct`.

**Comment by gcstang** [comment]
> Which ones are not cached? Please provide some cases.

I have a private repository that I want the proxy to also cache, maybe I'm not doing this properly.
Originally I had this as GOPRIVATE=<my internal repo> but obviously if I do that it won't try to connect to the proxy I wrote using your module.

What configuration do I need to supply to your proxy so it can connect to my internal repository?

Here is what my main.go looks like currently.

`g := goproxy.Goproxy{}
	dirCacher := goproxy.DirCacher("/Users/myuser/goproxycache")
	g.Cacher = dirCacher
	g.GoBinEnv = append(
		os.Environ(),
		"GOPROXY=direct,https://proxy.golang.org",
	)
	g.ProxiedSUMDBs = []string{"sum.golang.org"}
	
	http.ListenAndServe("localhost:8080", &g)`

Thank you

**Comment by aofei** [comment]
> Originally I had this as GOPRIVATE= but obviously if I do that it won't try to connect to the proxy I wrote using your module.

```go
g.GoBinEnv = append(
	os.Environ(),
	"GOPROXY=https://proxy.golang.org,direct",
	"GOPRIVATE=git.example.com,git.corp.example.com"
)
```

This's a correct way to use. All module paths prefixed with `git.example.com` or `git.corp.example.com` will go `direct`.

> When I try to use this I'm getting a DNS error for my Private Repo
> dial tcp: lookup on 8.8.8.8:53: no such host

This sounds like a problem with your local network environment. Where's your Goproxy program running?

**Comment by gcstang** [comment]
running on a Mac

**Comment by aofei** [comment]
> running on a Mac

On macOS or some container on it? If you can `dig host`, then your Goproxy program should also be able to lookup that host.

**Comment by gcstang** [comment]
directly on the Mac
