### ISSUE TITLE
/tmp required but not configurable 

### ISSUE THREAD

**Issue by P-S-bits** [goproxy/goproxy#27]
When running goproxy in a from scratch container it will fail to serve with the following message:

```
stat /tmp: no such file or directory
```

Client side it will be:
```
go mod download: github.com/aws/aws-sdk-go@v1.34.31: reading http://<proxy-url>/github.com/aws/aws-sdk-go/@v/v1.34.31.info: 500 Internal Server Error
```

I can't find in the go source the /tmp hardcoded anywhere, as such it is likely from an upstream library. 

Maybe mentioning this in the documentation is good enough

**Comment by aofei** [comment]
It's caused by [this](https://github.com/goproxy/goproxy/blob/9c110cff373c735b2b6d0a8a220eaf09125bd81a/goproxy.go#L408).

But it's really rare to see someone actually running a Go module proxy in a container where the `/tmp` doesn't exist.

**Comment by P-S-bits** [comment]
wow - thanks for the quick turnaround. I see it defaults to /tmp/ and adds the goproxy to the names it will create.

**Comment by aofei** [comment]
Thank you for reporting this issue, and a new field `Goproxy.TempDir` was added in https://github.com/goproxy/goproxy/commit/46e02efdb5e4d24b11e3719d2a472c1767a4709a.
