### ISSUE TITLE
可以使用 goproxy 解决私有 GitLab 仓库问题吗？

### ISSUE THREAD

**Issue by drrrMikado** [goproxy/goproxy#28]
公司的项目用到了内部 GitLab 的 PKG，导致 `docker build` 会拉不到，所以我想着使用该项目搭建一个公司的 goproxy，不知道能不能解决私有仓库问题。
有两个解决方案：

1. 配置 `.netrc` 
2. 配置 `ssh key` + `git config url."git@git.private".insteadOf "git.private.com"`

但是不知道这两套方案是否能够解决私有仓库问题，或者还有其他更好的方案吗？

**Comment by aofei** [comment]
> * 配置 `.netrc`
> * 配置 `ssh key` + `git config url."git@git.private".insteadOf "git.private.com"`

这两种方案均可。

注意默认情况下 `go get` 所发出的是 HTTPS 请求，此时你需要在 Goproxy 进程所属用户的 Home 目录下放置 `.netrc` 文件。如果 Home 目录下已经放置了 SSH 密钥，那大可采用第二种方案了。

**Comment by drrrMikado** [comment]
感谢

**Comment by drrrMikado** [comment]
@aofei 哈喽大佬，我这里 goproxy 现在遇到一个问题，访问 `http://goproxy.example.com/gitlab.private.com/dev/redigo/@v/list`，报 404 Not Found。公司其他私有包（go.mod 中的 module 写的是公司 GitLab 地址）是正常的。

该 `dev/redigo` 项目来自 fork GitHub 上的 `gomodule/redigo`，并 `dev/redigo` 中的 go.mod 并没有变动。

使用 `dev/redigo` 的方式：`replace github.com/gomodule/redigo => gitlab.private.com/dev/redigo v1.8.4`。

goproxy 使用的是 netrc，另外该账户也是有权限的，即`git ls-remote -q` 是有输出 tag 信息。

综上所述，是我遗漏了哪些步骤吗？

**Comment by aofei** [comment]
你的 `.netrc` 文件是在 Goproxy 进程所属环境用户的 Home 目录下吗？如果是的话，你可以试试相同环境下 `go list -m -versions -json gitlab.private.com/dev/redigo@latest` 是否可以正常返回结果。

另外，据我所知 GitLab 之前的版本存在有 Bug，所有 subgroup 级别的 repo 都不支持 `?go-get=1` 查询，因此 `go get` 等命令也就不能使用，你们 GitLab 的版本是多少？

**Comment by drrrMikado** [comment]
GitLab 版本：14.5.0
goproxy 部署方式： docker，用户 root

> go list -m -versions -json gitlab.private.com/dev/redigo@latest

goproxy 所属机器没配 `GOPRIVATE` 的环境变量，所以执行 `go list` 不能正常返回结果，但是另外加上 `GOPRIVATE=xxx go list` 就可以返回。

我这边启动 goproxy 进程是通过 `GoBinEnv` 配置 `GOPRIVATE=xx`。
代码：
```go
srv := &http.Server{
	Addr: cfg.ServerAddr,
	Handler: &server{
		Goproxy: &goproxy.Goproxy{
			// cfg.Environments 这里配置了 GOPROXY=xxx 、GOPRIVATE=xxx 、GOSUMDB=xxx
			GoBinEnv:            append(os.Environ(), cfg.Environments...),
			ProxiedSUMDBs:       cfg.ProxiedSUMDBs,
			Cacher:              cacher,
			CacherMaxCacheBytes: cfg.Cacher.MaxSize,
		},
	},
}
```

**Comment by aofei** [comment]
GitLab 的版本不存在任何问题，很新。

> 但是另外加上 `GOPRIVATE=xxx go list` 就可以返回。

指的是你在 Docker 容器内部执行 `go list` 时可以正常返回对吧？需要注意 `.netrc` 应该在 Docker 容器内部的 `/root/.netrc`，并非宿主机的。不过这点你应该也知道，顺便说一下以防万一。



> 我这边启动 goproxy 进程是通过 `GoBinEnv` 配置 `GOPRIVATE=xx`。

倒也不用把环境变量写进代码里，设置进程的环境变量即可。

总之，如果你手动执行 `go list` 是可以正常返回结果的，那么 Goproxy 的进程也应该可以正常获取才对。

**Comment by drrrMikado** [comment]
> 倒也不用把环境变量写进代码里，设置进程的环境变量即可。

有一个点很奇怪，即：`gitlab.private.com/dev/pkg2`，这个包是可以获取到的，即 `goproxy.example.com/gitlab.private.com/dev/pkg2/@v/list` 是有输出的。

**Comment by aofei** [comment]
你的 `GOPRIVATE` 是怎么设置的？你需要设置成 `GOPRIVATE=gitlab.private.com`。

**Comment by drrrMikado** [comment]
结案了。
> module path 和 module version 是存在 escape 机制的，大写字母需要 escape，比如 Dev 要被 escape 成 !dev。
