### ISSUE TITLE
goproxy 无法代理私有 GitLab多级子目录问题

### ISSUE THREAD

**Issue by JaminCui** [goproxy/goproxy#30]
一般go module和gitlab仓库都是三级，比如 mygitlab.com/group/myproject ，这种模式已测试可以正常代理，当仓库有多级子组的情况下，包层级会增加，如  mygitlab.com/group/subgroup/myproject 这种情况下无法代理
最后错误提示为：http://mygitlab.com/group/subgroup.git  not found

**Comment by aofei** [comment]
这实际上是 GitLab 老版本存在的一个已知 bug，现在已经被修复。请问你们的 GitLab 是什么版本？

**Comment by JaminCui** [comment]
GitLab 社区版 10.8.4

**Comment by aofei** [comment]
你们的版本实在是太老了，的确是问题版本，建议考虑升级。

**Comment by JaminCui** [comment]
公司git很多人用，升级不了啦，不过同事改了你的源码，思路大概就是在地址后面加上.git后缀，也算是解决问题了哈
参考链接：https://gitlab.com/gitlab-org/gitlab-foss/-/issues/30785
