### ISSUE TITLE
自建goproxy，私有包拉取不了

### ISSUE THREAD

**Issue by drrrMikado** [goproxy/goproxy#32]
具体问题描述：
1. 执行 go get 私有包报错
  ```
  go: downloading gitlab.private.com/group/eframe v0.0.0-20220313171137-8002bdaf0155
  go get gitlab.private.com/group/eframe@latest: gitlab.private.com/group/eframe@v0.0.0-20220313171137-8002bdaf0155: verifying module: gitlab.private.com/group/eframe@v0.0.0-20220313171137-8002bdaf0155: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/gitlab.private.com/group/eframe@v0.0.0-20220313171137-8002bdaf0155: 404 Not Found
        server response:
        not found: gitlab.private.com/group/eframe@v0.0.0-20220313171137-8002bdaf0155: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/gopath/pkg/mod/cache/vcs/8c183c5c7094a475fac32b3c6967730307b328c913f0052b5fbe1f1be7874107: exit status 128:
                fatal: could not read Username for 'https://gitlab.private.com': terminal prompts disabled
  ```

goproxy 结构：
```go
goproxy.Goproxy{
	GoBinEnv: append(os.Environ(),
		"GOPROXY=https://goproxy.cn,direct",
		"GOSUMDB=sum.golang.google.cn",
		"GOPRIVATE=gitlab.private.com",
	),
	ProxiedSUMDBs: "sum.golang.org https://goproxy.cn/sumdb/sum.golang.org",
}
```

在容器内执行 `git ls-remote -q http://gitlab.private.com/group/eframe.git` 是可以获取到的。
容器内执行 `GOPRIVATE=gitlab.private.com go get gitlab.private.com/group/eframe@latest` 也是正常的。

疑问点是：为啥会去 goproxy.cn/sumdb 读，已经配置 GOPRIVATE 了（感觉是代码中的 GoBinEnv 中的 GOPRIVATE 没有生效）

**Comment by drrrMikado** [comment]
本地执行报错，
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mikado/.cache/go-build"
GOENV="/home/mikado/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mikado/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mikado/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,http://goproxy.private.com,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/home/mikado/GoLabs/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1973494546=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by aofei** [comment]
嗯，这就是问题所在了。

注意看，你的 `GOPROXY` 环境变量是一个逗号列表，逗号列表的意思是“如果前一个代理返回了 404/410 响应，那就自动 fallback 到下一个代理“，所以在你的本地网络与 goproxy.cn 之间不存在任何障碍时，`go get` 使用的是 goproxy.cn。又因为你的 `GOSUMDB` 是默认的 `sum.golang.org`，所以在你本地的 `GONOSUMDB` 未正确配置时，`go get` 会使用 goproxy.cn 进行模块校验操作。

目前针对你的情况的解决办法，是将你们的私有模块 host 配置进本地的 `GONOSUMDB`。

**Comment by drrrMikado** [comment]
那这样的话，是不是有两种解决方案：
1. 把内部 goproxy 地址移至 `goproxy.cn` 前
2. 把内部 gitlab 地址添加至 `GONOSUMDB` 中

**Comment by aofei** [comment]
方案 1 还存在另外一个问题，就是你的 Goproxy 代码中还配置了个 `ProxiedSUMDBs: "sum.golang.org https://goproxy.cn/sumdb/sum.golang.org"`，这依然会导致你本地 `go get` 试图通过 `sum.golang.org` 去校验模块版本，这里需要注意你 Goproxy 所处环境的 `GOPRIVATE` 并不在这一步骤参与工作。

事实上，针对只是用私有代理的情况，建议是 `GOSUMDB=off`，因为所有的校验行为都应放在 Goproxy 所处的服务端去完成，这样所有本地客户端经过私有代理所获取到的模块版本都是 100% 可信任的，本地的模块校验反倒成了多余。

**Comment by drrrMikado** [comment]
了解了，感谢。 

所以是不是使用自建 goproxy 的话，都推荐在本地设置 `GOSUMDB` 或 `GONOSUMDB` ？

**Comment by aofei** [comment]
> 所以是不是使用自建 goproxy 的话，都推荐在本地设置 `GOSUMDB` 或 `GONOSUMDB` ？

公共代理，比如使用 goproxy.cn，本地建议保留 `GOSUMDB` 为其默认值 `sum.golang.org`（因为官方可信），另外配置 `GOPRIVATE` 来针对私有模块绕过 `GOPROXY` 和 `GOSUMDB`，或者分开单独配置 `GONOPROXY`/`GONOSUMDB`，`GOPRIVATE` 只是它俩的**默认值**而已。

私有代理，也就是使用通过 Goproxy 自建的，本地建议 `GOSUMDB=off`，因为模块数据校验行为应在私有代理所处的服务端完成。

公共代理、私有代理混合存在，也就是你的场景，就像前面说的建议的是在本地配置只配置 `GONOSUMDB`。

**Comment by drrrMikado** [comment]
好的，谢谢谢谢~
