### ISSUE TITLE
failed to list module versions

### ISSUE THREAD

**Issue by ptman** [goproxy/goproxy#34]
```
failed to list module versions: google.golang.org/protobuf/types@latest: go: module google.golang.org/protobuf/types: no matching versions for query "latest"
```

**Comment by aofei** [comment]
Is this log output by your `Goproxy`? If so, please see https://github.com/goproxy/goproxy/issues/6#issuecomment-557116589. TL;DR: this is normal.

**Comment by ptman** [comment]
Ok, but DirCacher doesn't seem to write anything.

**Comment by aofei** [comment]
It only caches data that really needs to be cached, currently only module files (`.info`, `.mod`, `.zip`).

**Comment by aofei** [comment]
Try this:

```bash
$ go clean -modcache
$ GOPROXY=<your-goproxy-endpoint> go get golang.org/x/text
$ ls <your-goproxy-cacher-dir>
```
