### ISSUE TITLE
代理有时会产生http2: server sent GOAWAY and closed the connection错误

### ISSUE THREAD

**Issue by vicnoah** [goproxy/goproxy#35]
cargo-warehouse imports
        github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 imports
        github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi imports
        gopkg.in/yaml.v2 tested by
        gopkg.in/yaml.v2.test imports
        gopkg.in/check.v1: gopkg.in/check.v1@v1.0.0-20200902074654-038fdea0a05b: http2: server sent GOAWAY and closed the connection; LastStreamID=199, ErrCode=NO_ERROR, debug=""

**Comment by aofei** [comment]
你好，请提供一下你的 Go 版本，你所提的这个问题应该是 Go 标准库里 HTTP/2 实现所存在的已知 bug，并非 Goproxy 这边导致的。

**Comment by vicnoah** [comment]
> 你好，请提供一下你的 Go 版本，你所提的这个问题应该是 Go 标准库里 HTTP/2 实现所存在的已知 bug，并非 Goproxy 这边导致的。

Go1.17.3版本

**Comment by aofei** [comment]
版本不存在问题。不过 Go 标准库里的 HTTP/2 实现的确存在一些已知 bug，你可以在[这里](https://github.com/golang/go/search?q=net%2Fhttp2+goaway&type=issues)看到。

针对这个问题目前最好的解决办法是只处理 HTTP/1.x 的请求。事实上目前 Go Web 开发场景中直接将 Go HTTP server 暴露出去的情况也挺少见，大部分都是跑在类似 Nginx 的反代后面，通常这些反代送给 Go HTTP server 的都只有 HTTP/1.x 请求，因此也就避免掉了上述问题。

由于问题与 Goproxy 实现无关，这个 issue 我就先关闭了。
