### ISSUE TITLE
无法拉取gitlab中的私有包

### ISSUE THREAD

**Issue by hjinbi** [goproxy/goproxy#37]
线上测试出现 go mod download: xx.xx.com/gitlab/xx/xx@v0.0.1: invalid version: unknown revision v0.0.1

下面是内部代理源码
```
func main() {

	err := http.ListenAndServe(":"+port, &goproxy.Goproxy{
		GoBinEnv: append(
			os.Environ(),
			"GOPROXY=https://goproxy.cn,direct", // 使用 Goproxy.cn 作为上游代理
			"GOPRIVATE=xx.xx.com/gitlab",     // 解决私有模块的拉取问题（比如可以配置成公司内部的代码源）
		),
		ProxiedSUMDBs: []string{
			"sum.golang.org https://goproxy.cn/sumdb/sum.golang.org", // 代理默认的校验和数据库
		},
	})
	if err != nil {
		log.Println(err)
		return
	}
}
```
拉取私有包的服务的ENV
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="http://自建代理ip:port,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.15"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2783035286=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by aofei** [comment]
如果只是单纯地好奇 log 内容的话，那你需要了解是那是模块路径推算行为中的正常请求，Go modules 是需要依赖 Goproxy 的 404/410 响应来实现模块路径推算的，具体行为请看 https://github.com/goproxy/goproxy/issues/6#issuecomment-557116589 这条回复。

如果确实无法 `go get` 到原本应该可达的模块，那你需要检查一下你的 GitLab 版本了，因为 GitLab 老版本的确存在已知的 subgroup bug，导致 `go get` 无法正常解析，详情请看 https://gitlab.com/gitlab-org/gitlab-foss/-/issues/30785 这个 issue。

**Comment by hjinbi** [comment]
不是好奇log内容，而且出现这个日志而且包无法拉取；
本地 `go  get`可达；Gitlab版本号`GitLab Community Edition [13.8.5]`；

**Comment by hjinbi** [comment]
对于多级路径的包`xx.xx.com/gitlab/aa/bb@v0.0.1`，将aa群组以及bb项目设置为公开后线上可以成功拉取。

**Comment by aofei** [comment]
除了你 Goproxy 进程的 `GOPRIVATE` 环境变量必须配置正确，此外还需要再额外为 Goproxy 进程所处的环境配置访问 GitLab 私有库的权限才行。比如通常是为 Git-Over-HTTPS 配置合适的 `~/.netrc` 或者为 Git-Over-SSH 配置合适的 SSH 密钥，在未能正确配置时的确会出现上述报错的情况。

**Comment by hjinbi** [comment]
下面是dockerfile，~/.netrc是配置了的，GOPRIVATE 也确认无误。。
```
FROM golang:1.16 AS runner

WORKDIR /usr/src/app

COPY ./go.mod /usr/src/app/

COPY ./go.sum /usr/src/app/

ENV GOPROXY=https://goproxy.cn,direct CGO_ENABLED=0 

RUN echo "machine xx.xx.com login xxx password xxx" >> ~/.netrc  && go mod download
```

**Comment by aofei** [comment]
这个 Dockerfile 是做什么的？`/usr/src/app` 指的是什么程序？OP 中的代码么？

**Comment by hjinbi** [comment]
goproxy 打包成容器运行的，环境变量在容器中指定

**Comment by aofei** [comment]
那你在 Dockerfile 中的启动 Goproxy 进程的前面加一句 `RUN go get xx.xx.com/gitlab/foo/bar` 看一下是否可以正常拉取你们的私有库。

**Comment by hjinbi** [comment]
`GOPRIVATE=xx.xx.com`变量不是在进程内部设置的吗？Dockerfile加一句RUN go get xx.xx.com/gitlab/foo/bar是拉取不了的，报的gosum check 错误.

**Comment by aofei** [comment]
我指的是为了验证在同样的容器环境下，你是否可以通过普通的 `go get` 命令拉取到你们私有库下的模块，如果不行的话，那 Goproxy 自然也是无法拉取到的，因为 Goproxy 的本质也是执行了一些类似 `go get` 的命令。

至于容器内的环境变量，你本该为普通的 `go get` 命令设置什么，就该为 Goproxy 设置什么，是一致的。

**Comment by hjinbi** [comment]
但是在启动 的Goproxy 进程内部有设置`GOPRIVATE=xx.xx.com`，只是构建Goproxy 进程没有`GOPRIVATE`
而且在给Dockerfile加上`ENV GOPRIVATE=xx.xx.com`，可以正常`go get xx.xx.com/gitlab/foo/bar`，但这种情况下，别的服务通过Goproxy也还是没有成功拉取私有库

**Comment by aofei** [comment]
那你可以绕过 `go` 命令直接通过 `curl -iv http://<goproxy-host>:<goproxy-port>/xx.xx.com/gitlab/foo/bar/@latest` 来验证你的 Goproxy 服务是否正常，如果返回了 200 响应就是正常。前面这个 URL 规则其实很简单，路径部分先是模块路径（注意大写字母要转译，比如 `A` 要变成 `!a`），然后跟个 `/@latest` 表示获取该模块的最新版本。

**Comment by hjinbi** [comment]
线上报的是404，但是我在本地拉取线上构建的Goproxy来运行，通过`curl -iv http://<goproxy-host>:<goproxy-port>/xx.xx.com/gitlab/foo/bar/@latest`访问，报的是200。

**Comment by aofei** [comment]
> 但是我在本地拉取线上构建的Goproxy来运行

我没理解这句话，指的是拉取线上构建的 Goproxy 服务，也就是那个 docker image 吗？

**Comment by hjinbi** [comment]
对，是线上的docker image

**Comment by aofei** [comment]
那说明你的线上环境的确存在问题，应该是环境并没有访问你们指定 GitLab 私有库的权限，从这方面入手检查吧。

**Comment by hjinbi** [comment]
好的，感谢

**Comment by hjinbi** [comment]
排查发现Goproxy以docker service 形式启动，会导致访问不了私有库，公有库正常；docker run 启动则没有问题；怀疑是docker 
 swarm network的问题;
