### ISSUE TITLE
goproxy responds with HTTP/1.0 on response to CONNECT, some clients do not support this

### ISSUE THREAD

**Issue by JesseStimpson** [goproxy/goproxy#38]
Hello,

While using the Erlang HTTP client [gun](https://github.com/ninenines/gun), I'm unable to make a successful connection to [smokescreen](https://github.com/stripe/smokescreen). `gun` is expecting the proxy server to respond only with HTTP/1.1 on the response to the CONNECT, but `goproxy` is [providing HTTP/1.0](https://github.com/stripe/goproxy/blob/master/https.go#L137).

I've reached out to the maintainer of gun[0] with the possibility of allowing this case on the client with an optional flag. But I also wanted to check in here to see if there is anything to address within goproxy.

Thanks,
Jesse

[0] [gun:connect expects proxy server to reply with HTTP/1.1...](https://github.com/ninenines/gun/issues/303)

**Comment by aofei** [comment]
Sorry sir, but I think you are looking for the wrong project.
