### ISSUE TITLE
支持导入路径的替换功能

### ISSUE THREAD

**Issue by haormj** [goproxy/goproxy#4]
### 概念
原始导入路径(original import path): 代码中的导入路径  
实际导入路径(actual import path): 引用代码实际的导入路径

### 举例

线上仓库地址为: code.haormj.xyz/go/dispatcher
本地项目导入路径为: haormj.xyz/go/dispatcher

目前要迁移到 go mod

#### 方案一

在`go.mod`中配置 replace 解决

```
module haormj.xyz/go/test

go 1.13

require (
	haormj.xyz/go/dispatcher v0.0.1 // indirect
)

replace haormj.xyz/go/dispatcher v0.0.1 => code.haormj.xyz/go/dispatcher v0.0.1
```

优点: golang 原生解决方案
缺点: 需要使用者手动配置(当然也可以通过脚本生成)

#### 方案二

配置`GOPROXY`透明完成`haormj.xyz`到`code.haormj.xyz`的切换

1. 目前 goproxy 的原理就是通过`go mod download`实现下载
2. 为了完成透明路径切换,需要完成一下内容
    - 将请求的路径 `haormj.xyz/go/dispatcher`替换为 `code.haormj.xyz/go/dispatcher`
    - 将`go mod download`后的路径`code.haormj.xyz/go/dispatcher`替换为`haormj.xyz/go/dispatcher`
    - 将对应的 zip 文件解压后重新按照`haormj.xyz/go/dispatcher`压缩
    - 替换对应`mod`文件中的内容

优点: 对使用者透明,只需配置`GOPROXY`即可
缺点: 代理出现问题,会导致无法使用 go module

**Comment by aofei** [comment]
严格意义上来讲 module path 的这个别名儿问题不应该交由 Go module proxy 去解决，因为它属于 Go modules 本身的设计问题，不过好消息是 Go team 目前正在着手于解决这个问题了，所以我就先关闭这个 issue 了哈，建议订阅：https://github.com/golang/go/issues/26904

此外，这个项目不同于 goproxy.cn，这个项目针对的主要群体不止是中国人，所以为了方便其他不懂中文的朋友查看 issue，建议以后以英文为主，不过无论如何还是谢谢你能来这儿提建议😊
