### ISSUE TITLE
is there a changelog?

### ISSUE THREAD

**Issue by liuxb980** [goproxy/goproxy#41]
I'm using 0.2.2 version, I want to upgrade it to 0.13, but I don't know what differences are between the two version.
I couldn't found a full log from 0.2 to 0.13.

Could someone describe the differences roughly please ?

**Comment by aofei** [comment]
Well, unfortunately, the changelog is only available starting from `v1.10.1`. But the core functionality of the Go module proxy has remained stable, even with some changes to the implementation. I recommend just using the latest `v0.16.1` if you can, as we are about to reach `v1.0.0`, at which point we will provide compatibility guarantees.
