### ISSUE TITLE
support /@latest endpoint

### ISSUE THREAD

**Issue by futurist** [goproxy/goproxy#43]
According to [GOPROXY protocol](https://go.dev/ref/mod#goproxy-protocol), `/@latest` is optional, but it is helpful if can add it.
The use case will be any usage without the `go` sub-command, like request the endpoint from HTTP.

**Comment by aofei** [comment]
`/@latest` has been supported since the beginning. What problem are you having? Let's see if I can help.

**Comment by futurist** [comment]
Is there any way don't depend the `doDirect` that will call a `go list -m -json`? Like something using API call directly.

**Comment by aofei** [comment]
> using API call directly.

What do you mean by that? Are you referring to using an upstream proxy? You can configure upstream proxies by setting the `GOPROXY` environment variable for your Goproxy process, e.g. `goproxy.Goproxy { GoBinEnv: []string{"https://goproxy.cn"} }` will prevent your Goproxy process from calling external `go` commands. All module fetch requests will be handled by goproxy.cn.

**Comment by aofei** [comment]
Since the answer has been provided, and there has been no new activity for a while, I'm going to close this issue. Feel free to open new issues at any time if you have other questions.
