### ISSUE TITLE
[BUG] go get stuck and server output git error

### ISSUE THREAD

**Issue by adlternative** [goproxy/goproxy#44]
I have set up a server on localhost:9080 using goproxy, but it gets stuck when I try to execute go get.

client:
```shell
GOPROXY=http://localhost:9080 go get gitlab.xxx.com/aaa/bbb@latest
go: downloading gitlab.xxx.com/aaa/bbb v0.0.0-20230815123511-328a75f65a51
```

server log:
```shell
2023/08/31 19:01:53 goproxy.go:391: goproxy: failed to list module version: gitlab.xxx.com/@v/list: module xxx.com: git ls-remote -q origin in /Users/adl/go/pkg/mod/cache/vcs/73e7c5efccc154f70f696b7ea0cb7a2a8e4f7960832a7bf61d0232685fc3163e: exit status 128:
	fatal: no path specified; see 'git help pull' for valid url syntax
2023/08/31 19:01:54 goproxy.go:391: goproxy: failed to list module version: gitlab.xxx.com/bbb/@v/list: module gitlab.xxx/bbb: git ls-remote -q origin in /Users/adl/go/pkg/mod/cache/vcs/f56dcfdca177b425cf074e4d7907ec28d80ec30aee1b92f4f93290aa4b447dec: exit status 128:
	fatal: protocol error: bad line length character: repo
```

server code:
```go
	http.ListenAndServe(":9080", &goproxy.Goproxy{
		GoBinEnv: append(
			os.Environ(),
			"GOPROXY=https://goproxy.cn",  // 使用 Goproxy.cn 作为上游代理
			"GOPRIVATE=*.xxx.com", // 解决私有模块的拉取问题（比如可以配置成公司内部的代码源）
		),
		ProxiedSUMDBs: []string{
			"sum.golang.org https://goproxy.cn/sumdb/sum.golang.org", // 代理默认的校验和数据库
		},
		ErrorLogger: logger,
	})
```

ENV:
```shell
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adl/Library/Caches/go-build"
GOENV="/Users/adl/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adl/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adl/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bj/t_584mj969b8zchzmqh_l4xh0000gp/T/go-build3868987923=/tmp/go-build -gno-record-gcc-switches -fno-common"

$ git version
git version 2.39.2 (Apple Git-143)
```

**Comment by aofei** [comment]
Sorry for the late response, I missed the email. 

> server log:
> 
> ```shell
> 2023/08/31 19:01:53 goproxy.go:391: goproxy: failed to list module version: gitlab.xxx.com/@v/list: module xxx.com: git ls-remote -q origin in /Users/adl/go/pkg/mod/cache/vcs/73e7c5efccc154f70f696b7ea0cb7a2a8e4f7960832a7bf61d0232685fc3163e: exit status 128:
> 	fatal: no path specified; see 'git help pull' for valid url syntax
> 2023/08/31 19:01:54 goproxy.go:391: goproxy: failed to list module version: gitlab.xxx.com/bbb/@v/list: module gitlab.xxx/bbb: git ls-remote -q origin in /Users/adl/go/pkg/mod/cache/vcs/f56dcfdca177b425cf074e4d7907ec28d80ec30aee1b92f4f93290aa4b447dec: exit status 128:
> 	fatal: protocol error: bad line length character: repo
> ```

Please be aware that these two lines of server logs you provided are expected. It's just how Go modules work. See https://github.com/goproxy/goproxy/issues/6#issuecomment-557116589 for details.

As for you mentioning that you're stuck on `go get`, my guess is that there's a problem with your server side network. I'm not sure, I'd need more details.

**Comment by aofei** [comment]
Hi @bilus, thanks for the great analysis!

Are your Goproxy process and `go mod tidy` running in the same environment? If so, try running them with different `GOMODCACHE`.

For example:

```bash
GOMODCACHE=/tmp/goproxy-gomodcache go run goproxy.go
```

and

```bash
GOMODCACHE=/tmp/gomodtidy-gomodcache go mod tidy
```

It seems there might be a deadlock somewhere. Might be something to do with `go run`'s process tree, I'll look into it later.

**Comment by aofei** [comment]
Yup, it's caused by a deadlock in `GOMODCACHE`, and it's 100% reproducible.

Start a Goproxy server:

```bash
GOPROXY=direct GOMODCACHE=/tmp/goproxy-gomodcache \
  go run github.com/goproxy/goproxy/cmd/goproxy@latest \
  server --address localhost:8080 --cacher-dir /tmp/goproxy-caches
```

Fetch something:

```bash
GOPROXY=http://localhost:8080 GOMODCACHE=/tmp/goproxy-gomodcache \
  go mod download -json golang.org/x/text@v0.14.0
```

Then it gets stuck.

Run `lsof | grep "/tmp/goproxy-gomodcache"`, you should be able to see two processes holding the same lock file:

```
... /tmp/goproxy-gomodcache/cache/download/golang.org/x/text/@v/v0.14.0.lock
... /tmp/goproxy-gomodcache/cache/download/golang.org/x/text/@v/v0.14.0.lock
```

While this is true, I don't consider it a bug; it's more like an edge case. This is because, in most cases, Goproxy should be run in a dedicated environment, such as a container. More importantly, this locking mechanism prevents duplicate VCS cloning operations, which is actually quite beneficial.

However, it definitely needs be mentioned in the docs that Goproxy should always have its own `GOMODCACHE`.

**Comment by bilus** [comment]
Thanks for a super quick response, I appreciate it.

Yes, it should be mentioned in the documentation, it cost me a lot of time to figure it out. Also, you could easily time out and report & log an error. Thirdly, there's too little logging available, please consider adding an option to turn on debugging logs (including setting `-x` flag to go mod).

**Comment by aofei** [comment]
Additional flags can be set via `GOFLAGS`. For example, `GOFLAGS=-modcacherw` works great for me.

Enabling verbose logging for `go` command calls can be a bit tricky since we can't simply redirect `exec.Cmd.Stderr` to `os.Stderr`. I'll need some time to figure out the best approach for achieving this.
