### ISSUE TITLE
拉取私有仓库问题

### ISSUE THREAD

**Issue by zhaoshouli** [goproxy/goproxy#45]
在做了私有仓库转发后包可以正常被拉去，但是以.git为前缀的文件都被删除了
例如：原文件.gitignore 拉下来后变为ignore
期待大佬的解答

**Comment by aofei** [comment]
抱歉晚回复了。这个问题还没遇见过，你确定是这个项目的某个 bug 导致的吗？如果确定的话麻烦提供一下更多细节方便我们来排查。

**Comment by zhaoshouli** [comment]
感谢你的回复，已经解决了，是我的改动引起的
