### ISSUE TITLE
Dockerfile go version 需要更新

### ISSUE THREAD

**Issue by hunshcn** [goproxy/goproxy#57]
`go list -json -m -versions modulePath`

需要保证 go 的 patch version >= targetModule 的 go 的 patch version。

当前 alpine 3.19 的 go 是 1.21.10。在 direct 下，`/@v/list` 就无法正常工作，所以可能需要让 Dockerfile From 最新版本的 golang alpine 而不是 base alpine 做 apk add

这个错误可以使用低于 1.22.3 go 的版本执行 `GOPROXY=direct go list -json -m -versions github.com/hunshcn/go-test-repo@latest` 复现

会出现下面这样的错误
```
go: loading module retractions for github.com/hunshcn/go-test-repo@v0.0.2: module github.com/hunshcn/go-test-repo@v0.0.2 requires go >= 1.22.3 (running go 1.22.1)
```

话说 goproxy.cn 线上没有问题，是 upstream 为 proxy.golang.org 吗

**Comment by hunshcn** [comment]
patch version 会比较频繁，针对线上场景还有一个方法是保证 minor version 不落后，然后通过定期+异常捕获的形式触发 go 最新版本的获取，然后指定 GOTOOLCHAIN，比如可以用 go1.22.1 通过
```
GOTOOLCHAIN=go1.22.3 GOPROXY=direct go list -json -m -versions github.com/hunshcn/go-test-repo@latest
```
GOTOOLCHAIN 指定新的版本以解决这个错误。只是不能跨 minor version

**Comment by aofei** [comment]
非常不好意思邮件太早 archive 导致我忘记回复（我以为我回复过了😅）。今天看到 `GOTOOLCHAIN` 相关的问题突然想起来了你这个 issue。。。

这个问题应该算作是 go 本身的 bug，刚才去翻了翻发现已经有人在修了：[CL588775](https://go.dev/cl/588775)。

预计到  Go 1.23 应该就不存在这个问题了，所以在这之前咱们可以先 bump 一下 base image 的版本到 `alpine:3.20` 来临时处理下。你觉着呢？

**Comment by hunshcn** [comment]
alpine:3.20 或者直接使用 golang:alpine 都可以，他们都是最新的 1.22.4

**Comment by aofei** [comment]
那先用 alpine:3.20 然后走 apk 来安装 go 吧。不打算依赖 golang:alpine，后面计划移除对外部 go 命令的依赖。有空的话可以提个 PR 吗？或者等我晚上来修也行。

**Comment by hunshcn** [comment]
https://github.com/golang/go/issues/68052 已经被 backport to 1.22 并且在 1.22.5 中发布

**Comment by aofei** [comment]
> [golang/go#68052](https://github.com/golang/go/issues/68052) 已经被 backport to 1.22 并且在 1.22.5 中发布

👍感谢提醒！已发布 [v0.17.1](https://github.com/goproxy/goproxy/releases/tag/v0.17.1)。不过 `ghcr.io/goproxy/goproxy:0.17.1` 里还是 Go 1.22.4，因为 `alpine:3.20` 那边没有 bump go 的版本（失策😅）。等到 Alpine 那边更新了再放个版吧。
