### ISSUE TITLE
Proxy not working properly

### ISSUE THREAD

**Issue by pedrobisp** [goproxy/goproxy#6]
Right now when I try to use go get, the proxy cannot parse the git URLs properly.

For example, if I run 

```
go get github.com/bazelbuild/bazelisk
```

I obtain this in the proxy handler

```
2019/11/21 15:17:43 mod list github.com/bazelbuild@latest: go list -m: github.com/bazelbuild@latest: invalid github.com/ import path "github.com/bazelbuild"
2019/11/21 15:17:43 mod list github.com@latest: go list -m: github.com@latest: unrecognized import path "github.com" (parse https://github.com/?go-get=1: no go-import meta tags ())
```

Any clues on what is causing the issue? Am missing the setup of something?

**Comment by aofei** [comment]
I just tried this:

```go
package main

import (
	"net/http"
	"os"

	"github.com/goproxy/goproxy"
)

func main() {
	g := goproxy.New()
	g.GoBinEnv = append(
		os.Environ(),
		"GOPROXY=direct",
		"GOSUMDB=off",
	)

	http.ListenAndServe("localhost:8080", g)
}
```

```bash
$ GOPROXY=http://localhost:8080 go get github.com/bazelbuild/bazelisk
go: finding github.com/bazelbuild/bazelisk v1.1.0
go: downloading github.com/bazelbuild/bazelisk v1.1.0
go: extracting github.com/bazelbuild/bazelisk v1.1.0
go: downloading github.com/hashicorp/go-version v1.1.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/hashicorp/go-version v1.1.0
go: finding github.com/hashicorp/go-version v1.1.0
go: finding github.com/mitchellh/go-homedir v1.1.0
```

It seems that everything is working fine. I didn't see any errors.

If you're curious why you got these logs:

```bash
2019/11/21 22:29:17 mod list github.com/bazelbuild@latest: go list -m: github.com/bazelbuild@latest: invalid github.com/ import path "github.com/bazelbuild"
2019/11/21 22:29:18 mod list github.com@latest: go list -m: github.com@latest: unrecognized import path "github.com" (parse https://github.com/?go-get=1: no go-import meta tags ())
```

Then you need to know that they are normal messages. This is just how Go modules work. It calculates and derives the module path based on the import path in your code.

When you run `go get github.com/bazelbuild/bazelisk`, the Go modules tries to find the module(s) (**concurrently**) at three addresses: `github.com/bazelbuild/bazelisk`, `github.com/bazelbuild`, and `github.com`. Only the first address represents a module, so you got those two logs.

This is fine, just ignore those two logs. There is nothing to worry about. 😄

**Comment by pedrobisp** [comment]
Sorry, my bad, it was a messed up local setup with wrong environment variables. Thanks for the fast reply!
