### ISSUE TITLE
Please use virtual hosted style to access

### ISSUE THREAD

**Issue by bestneymarjr** [goproxy/goproxy#7]
I want to use oss cacher, what should the endpoint set up?

**Comment by aofei** [comment]
Sorry, there is a bug in Alibaba Cloud OSS (as far as I know, they have this bug, see: https://github.com/minio/minio-go/issues/1119#issuecomment-499967248). I've reported it to Alibaba Cloud through a work order couple months ago and they've promised to fix it, but now it looks like they did nothing.

**Comment by bestneymarjr** [comment]
Thank you very much for your reply. May I understand this? I cannot use oss unless I change the code.

**Comment by bestneymarjr** [comment]
When I add the bucket name to the endpoint,there is a new error , The specified key does not exist.
This error return from m.client.PutObjectWithContext.

**Comment by aofei** [comment]
> May I understand this? I cannot use oss unless I change the code.

You can use Alibaba Cloud's [OSS SDK](https://godoc.org/github.com/aliyun/aliyun-oss-go-sdk/oss) to implement a [goproxy.Cacher](https://godoc.org/github.com/goproxy/goproxy#Cacher) and a [goproxy.Cache](https://godoc.org/github.com/goproxy/goproxy#Cache) yourself. This's should be pretty easy. You can refer to [this](https://github.com/goproxy/goproxy/blob/09c1d800c4274b449d87860e1ea0f5c3205410ac/cachers/oss.go) if you want (need to be refined).

**Comment by bestneymarjr** [comment]
thank you

**Comment by aofei** [comment]
Alibaba Cloud just told me that they're gradually releasing a new version of this bug that has been fixed. At present, only some regions have adopted the new version.

**Comment by aofei** [comment]
They plan to cover all regions with the new version next month.

**Comment by bestneymarjr** [comment]
I got it,thanks

**Comment by bestneymarjr** [comment]
I use your [oss cacher](https://github.com/goproxy/goproxy/blob/09c1d800c4274b449d87860e1ea0f5c3205410ac/cachers/oss.go) implement by  Alibaba Cloud's OSS SDK, and I updated [it](https://github.com/bestneymarjr/hello_world/blob/master/oss.go),
now I can put the object to aliclould, but when I go get a project,there is a error: zip: not a valid zip file.

**Comment by bestneymarjr** [comment]
when I use disk cacher, nothing is error.

**Comment by aofei** [comment]
I said that [this](https://github.com/goproxy/goproxy/blob/09c1d800c4274b449d87860e1ea0f5c3205410ac/cachers/oss.go) needs to be refined. I just refined a version for you, you can refer to the following code (untested):

```go
// ossCache implements the `goproxy.Cache`. It is the cache unit of the `OSS`.
type ossCache struct {
	sync.Mutex

	bucket     *oss.Bucket
	objectName string
	readCloser io.ReadCloser
	offset     int64
	closed     bool
	name       string
	mimeType   string
	size       int64
	modTime    time.Time
	checksum   []byte
}

// resetReadCloser resets the `oc.readCloser`.
func (oc *ossCache) resetReadCloser() error {
	if oc.readCloser != nil {
		if err := oc.readCloser.Close(); err != nil {
			return err
		}
	}

	var err error
	oc.readCloser, err = oc.bucket.GetObject(
		oc.objectName,
		oss.Range(oc.offset, oc.size),
	)

	return err
}

// Read implements the `goproxy.Cache`.
func (oc *ossCache) Read(b []byte) (int, error) {
	oc.Lock()
	defer oc.Unlock()

	if oc.closed {
		return 0, os.ErrClosed
	} else if oc.offset >= oc.size {
		return 0, io.EOF
	}

	if oc.readCloser != nil {
		if err := oc.resetReadCloser(); err != nil {
			return 0, err
		}
	}

	n, err := oc.Read(b)
	oc.offset += int64(n)

	return n, err
}

// Seek implements the `goproxy.Cache`.
func (oc *ossCache) Seek(offset int64, whence int) (int64, error) {
	oc.Lock()
	defer oc.Unlock()

	if oc.closed {
		return 0, os.ErrClosed
	}

	switch whence {
	case io.SeekStart:
	case io.SeekCurrent:
		offset += oc.offset
	case io.SeekEnd:
		offset += oc.size
	default:
		return 0, errors.New("invalid whence")
	}

	if offset < 0 {
		return 0, errors.New("negative position")
	}

	oc.offset = offset
	if oc.offset < oc.size {
		if err := oc.resetReadCloser(); err != nil {
			return 0, err
		}
	}

	return oc.offset, nil
}

// Close implements the `goproxy.Cache`.
func (oc *ossCache) Close() error {
	oc.Lock()
	defer oc.Unlock()

	if oc.closed {
		return os.ErrClosed
	}

	if oc.readCloser != nil {
		if err := oc.readCloser.Close(); err != nil {
			return err
		}
	}

	oc.closed = true

	return nil
}

// Name implements the `goproxy.Cache`.
func (oc *ossCache) Name() string {
	return oc.name
}

// MIMEType implements the `goproxy.Cache`.
func (oc *ossCache) MIMEType() string {
	return oc.mimeType
}

// Size implements the `goproxy.Cache`.
func (oc *ossCache) Size() int64 {
	return oc.size
}

// ModTime implements the `goproxy.Cache`.
func (oc *ossCache) ModTime() time.Time {
	return oc.modTime
}

// Checksum implements the `goproxy.Cache`.
func (oc *ossCache) Checksum() []byte {
	return oc.checksum
}
```
