### ISSUE TITLE
sumdb lookup 502

### ISSUE THREAD

**Issue by bestneymarjr** [goproxy/goproxy#8]
verifying github.com/dreamans/guuid@v0.0.0-20180321142257-7d0b13a43adc: github.com/dreamans/guuid@v0.0.0-20180321142257-7d0b13a43adc: reading http://localhost:8080/sumdb/sum.golang.org/lookup/github.com/dreamans/guuid@v0.0.0-20180321142257-7d0b13a43adc: 502 Bad Gateway

sumdb lookup timeout,the server can not connect sum.golang.org

**Comment by bestneymarjr** [comment]
This problem doesn't happen every time

**Comment by aofei** [comment]
That's because Goproxy has built-in support for `GOPROXY`, `GONOPROXY`, `GOSUMDB`, `GONOSUMDB` and `GOPRIVATE`, and there're default values for `GOPROXY` and `GOSUMDB` (see [this](https://github.com/goproxy/goproxy#features)). So maybe you need to change the default values:

```bash
$ GOPROXY=direct GOSUMDB=off <your-program>
```

or

```go
package main

import (
	"net/http"
	"os"

	"github.com/goproxy/goproxy"
)

func main() {
	g := goproxy.New()
	g.GoBinEnv = append(
		os.Environ(),
		"GOPROXY=direct",
		"GOSUMDB=off",
	)

	http.ListenAndServe("localhost:8080", g)
}
```

**Comment by aofei** [comment]
> verifying github.com/dreamans/guuid@v0.0.0-20180321142257-7d0b13a43adc: github.com/dreamans/guuid@v0.0.0-20180321142257-7d0b13a43adc: reading http://localhost:8080/sumdb/sum.golang.org/lookup/github.com/dreamans/guuid@v0.0.0-20180321142257-7d0b13a43adc: 502 Bad Gateway
> ...

And this's because Goproxy supports reverse proxy checksum databases. It's indicated by the `Goproxy.SupportedSUMDBNames`, defaulted to `["sum.golang.org"]`, maybe you need to change this too.

**Comment by aofei** [comment]
The `Goproxy.SupportedSUMDBNames` has been renamed to the `Goproxy.ProxiedSUMDBNames` and has no default value now. See [`Goproxy`](https://godoc.org/github.com/goproxy/goproxy#Goproxy) for details.

**Comment by bestneymarjr** [comment]
what's the Goproxy.ProxiedSUMDBNames mean?

My understanding is proxying sumbd request. But [this](https://github.com/goproxy/goproxy/blob/93d07b5deef8cb8ee2d036878a6c5a56fbb049a1/goproxy.go#L328) just use a http.client to request sumdbURL, not use proxy .

**Comment by bestneymarjr** [comment]
Maybe i understand it wrong

**Comment by aofei** [comment]
See this: http://golang.org/design/25530-sumdb#proxying-a-checksum-database

**Comment by bestneymarjr** [comment]
thanks,it is my fault
